import { describe, expect, it } from 'vitest';
import {
  assertNotBlocked,
  detectPlatform,
  isShareLink,
  parseClaudeMarkdown,
  parseDeepSeekMarkdown,
  parseDoubaoMarkdown,
} from './linkParser';
import { ParseError } from './types';

const CLAUDE_FIXTURE = `Title: Claude

URL Source: https://claude.ai/share/xxx

Markdown Content:
Your first chat with Claude

Shared by someone

This is a copy of a chat between Claude and someone. Content may include unverified or unsafe content.

Report

## You said: 今天天气怎么样?

帮我看看今天的天气

## Claude responded: 你好!

今天天气不错。

**建议**:
- 带伞
- 多喝水

## You said: 那明天呢

## Claude responded: 明天也还行
`;

const DEEPSEEK_FIXTURE = `Title: 来自分享的对话 - DeepSeek

URL Source: https://chat.deepseek.com/share/xxx

Markdown Content:
Shared Conversation
Expert
Shared Conversation
Expert
This shared conversation is generated by AI, for reference only.
帮我写一个 Python 快速排序
Thought for 3 seconds
用户想要一个快速排序的实现,我应该给出代码示例。
好的,快速排序如下:

\`\`\`python
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    return quicksort([x for x in arr if x < arr[0]]) + [arr[0]] + quicksort([x for x in arr if x > arr[0]])
\`\`\`
`;

const DOUBAO_FIXTURE = `Title: 如何提升学习效率? - 豆包

URL Source: https://www.doubao.com/thread/xxx

Markdown Content:
提升学习效率的核心是**专注**和**反馈**。

- 番茄工作法
- 主动回忆
- 间隔重复
`;

describe('detectPlatform / isShareLink', () => {
  it('识别各平台 host', () => {
    expect(detectPlatform('https://claude.ai/share/abc')).toBe('claude');
    expect(detectPlatform('https://chat.deepseek.com/share/abc')).toBe('deepseek');
    expect(detectPlatform('https://www.doubao.com/thread/abc')).toBe('doubao');
    expect(detectPlatform('https://chatgpt.com/s/abc')).toBe('chatgpt');
    expect(detectPlatform('https://share.gemini.google/abc')).toBe('gemini');
  });

  it('非链接返回 null', () => {
    expect(detectPlatform('随便一段文字')).toBeNull();
    expect(detectPlatform('https://example.com/x')).toBe('unknown');
  });

  it('isShareLink', () => {
    expect(isShareLink('https://claude.ai/share/abc')).toBe(true);
    expect(isShareLink('用户: 你好')).toBe(false);
  });
});

describe('parseClaudeMarkdown', () => {
  it('解析多轮对话', () => {
    const r = parseClaudeMarkdown(CLAUDE_FIXTURE);
    expect(r.source).toBe('link');
    expect(r.messages).toHaveLength(4);
    expect(r.messages[0]).toMatchObject({ role: 'user', content: '今天天气怎么样?\n\n帮我看看今天的天气' });
    expect(r.messages[1]).toMatchObject({ role: 'assistant' });
    expect(r.messages[1].content).toContain('今天天气不错');
    expect(r.messages[1].content).toContain('- 带伞');
    expect(r.messages[3]).toMatchObject({ role: 'assistant', content: '明天也还行' });
  });

  it('标题行直接带内容', () => {
    const md = 'Markdown Content:\n## You said: 你好\n## Claude responded: 你好!有什么可以帮你?';
    const r = parseClaudeMarkdown(md);
    expect(r.messages[0].content).toBe('你好');
    expect(r.messages[1].content).toBe('你好!有什么可以帮你?');
  });

  it('无消息抛错', () => {
    expect(() => parseClaudeMarkdown('Markdown Content:\nSome random text')).toThrow(ParseError);
  });
});

describe('parseDeepSeekMarkdown', () => {
  it('解析用户消息与 AI 回答(含思考过程)', () => {
    const r = parseDeepSeekMarkdown(DEEPSEEK_FIXTURE);
    expect(r.messages).toHaveLength(2);
    expect(r.messages[0]).toMatchObject({ role: 'user', content: '帮我写一个 Python 快速排序' });
    expect(r.messages[1].role).toBe('assistant');
    expect(r.messages[1].content).toContain('好的,快速排序如下');
  });

  it('无 Thought 标记抛错', () => {
    const md = 'Markdown Content:\n只有一段文字没有标记';
    expect(() => parseDeepSeekMarkdown(md)).toThrow(ParseError);
  });
});

describe('parseDoubaoMarkdown', () => {
  it('用标题作为用户消息', () => {
    const r = parseDoubaoMarkdown(DOUBAO_FIXTURE);
    expect(r.title).toBe('如何提升学习效率?');
    expect(r.messages[0]).toMatchObject({ role: 'user', content: '如何提升学习效率?' });
    expect(r.messages[1]).toMatchObject({ role: 'assistant' });
    expect(r.messages[1].content).toContain('番茄工作法');
  });

  it('缺内容抛错', () => {
    expect(() => parseDoubaoMarkdown('Markdown Content:')).toThrow(ParseError);
  });
});

describe('assertNotBlocked', () => {
  it('检测登录墙', () => {
    expect(() =>
      assertNotBlocked('Markdown Content:\nGet responses tailored to you\nLog in to get answers'),
    ).toThrow(ParseError);
  });

  it('检测反爬页', () => {
    expect(() => assertNotBlocked('Markdown Content:\nCheck your internet connection and try again')).toThrow(
      ParseError,
    );
  });

  it('正常内容不抛错', () => {
    const normal = [
      'Markdown Content:',
      'Your first chat with Claude',
      '',
      '## You said: 今天天气怎么样?',
      '帮我看看今天的天气,顺便问一下明天会下雨吗?',
      '## Claude responded: 你好!',
      '今天天气不错,建议带伞出门。明天预计多云,大概率不会下雨,',
      '不过建议出门前再看一眼天气预报,这样更稳妥一些。',
    ].join('\n');
    expect(() => assertNotBlocked(normal)).not.toThrow();
  });
});
